//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FußballBestellung
{
    using System;
    using System.Collections.Generic;
    using System.Windows.Media;

    public partial class Customer
    {
        public string ID { get; set; }
        public string LastName { get; set; }
        public string FirstName { get; set; }
        public string Phone { get; set; }
        public string Street { get; set; }
        public Nullable<decimal> HouseNumber { get; set; }
        public Nullable<decimal> Postal { get; set; }
        public string City { get; set; }
        public string ChosenPayment { get; set; }
        public Color BoxColor { get; set; }
        public PayPal Paypal { get; set; }
        public BankAccount BankAccount { get; set; }

        public Customer()
        {

        }

        public Customer(string lastName, string firstName, string phone, string street, Nullable<decimal> houseNumber, Nullable<decimal> postal, string city)
        {
            this.LastName = lastName;
            this.FirstName = firstName;
            this.Phone = phone;
            this.Street = street;
            this.HouseNumber = houseNumber;
            this.Postal = postal;
            this.City = city;
        }

        public Customer(string lastName, string firstName, string phone, string street, int houseNumber, int postal, string city, Color boxColor)
        {
            this.LastName = lastName;
            this.FirstName = firstName;
            this.Phone = phone;
            this.Street = street;
            this.HouseNumber = houseNumber;
            this.Postal = postal;
            this.City = city;
            this.BoxColor = boxColor;
        }
    }
}
