//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FußballBestellung
{
    using System;
    using System.Collections.Generic;
    
    public partial class Table_Footballs
    {
        public decimal ID { get; set; }
        public string Name { get; set; }
        public Nullable<decimal> Size { get; set; }
        public string Brand { get; set; }
        public Nullable<double> Price { get; set; }
        public Nullable<decimal> Amount { get; set; }
        public string ImagePath { get; set; }
    }
}
